In [1]:
import numpy as np


one_list = np.ones((3,3))

In [82]:
import numpy as np

def m_n_matrix(matrix) : 
    shape_tuple =np.shape(matrix)
    print(matrix)
    new_matrix = np.zeros(shape_tuple)
    print(new_matrix)
    for i,one_1 in enumerate(matrix) :
        for j, one_2 in enumerate(one_1) : 
            
            if i == 0 and j == 0 : 
                print(i,j)
                new_matrix[i][j] =1
            elif i == 0  : 
                if matrix[i][j] == 1 and matrix[i][j-1] :
                    new_matrix[i][j] = matrix[i][j]
                else : pass
            elif j == 0 :
                if matrix[i][j] == 1 and matrix[i-1][j] :
                    new_matrix[i][j] = matrix[i][j]
                else : pass
            
            elif matrix[i][j] == 0 : 
                pass
            else :
                print(i,j)
                new_matrix[i][j] = new_matrix[i][j-1] + new_matrix[i-1][j]
    print(new_matrix)
    return new_matrix[-1][-1]

def solution(m, n, puddles):
    answer = 0
    #sum_num = m_n_matrix(m,n)
    del_list = []
    one_list = np.ones((m,n))
    
    for puddle in puddles : 
        x_ = puddle[0]
        y_ = puddle[1]
        one_list[x_-1,y_-1] = 0 
    

    answer = m_n_matrix(one_list)
    v,answer = divmod(answer, 1000000007)
    return answer

In [85]:
solution(5,4,[[2,1],[2,2],[2,3],[4,2],[4,3],[4,4]])

[[1. 1. 1. 1.]
 [0. 0. 0. 1.]
 [1. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
0 0
1 3
2 1
2 2
2 3
4 1
4 2
4 3
[[1. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 1. 1. 1.]]


1.0

In [86]:
one_list[1][4] = one_list[1-1][4] + one_list[1][4-1]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [43]:
one_list[1][4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [44]:
one_list[1]

array([1., 2., 3., 4.])